# create configmap with source data for pykb runner
apiVersion: v1
kind: ConfigMap
metadata:
  name: pykb-config
  namespace: kb-burner
data:
  config.yaml: |
    runs:
      - iterations: 4
        churn-duration: 10m
        churn-delay: 15m
      - iterations: 6
        churn-duration: 10m
        churn-delay: 45m
      - iterations: 5
        churn-duration: 10m
        churn-delay: 30m
      - iterations: 4
        churn-duration: 10m
        churn-delay: 15m
      - iterations: 10
        churn-duration: 10m
        churn-delay: 45m
      - iterations: 1
        churn-duration: 10m
        churn-delay: 30m

---
# job to start the runner
apiVersion: batch/v1
kind: Job
metadata:
  name: pykb-runner
  namespace: kb-burner
spec:
  template:
    spec:
      serviceAccountName: kube-burner-user
      containers:
        - name: pykb-runner
          image: quay.io/elmiko/pykb-runner:latest
          pullPolicy: Always
          volumeMounts:
            - name: config
              mountPath: "/etc/pykb-runner"
              readOnly: true
      restartPolicy: Never
      volumes:
        - name: config
          configMap:
            name: pykb-config
  backoffLimit: 4
