cluster_api_cluster = "casmod-p2c1-h8gzk"
machineset_basename = "casmod-p2c1-ms-"
instance_types = [
    'c5.xlarge', 'c5.2xlarge', 'c5.4xlarge',
    'c5a.xlarge', 'c5a.2xlarge', 'c5a.4xlarge',
    'm5.large', 'm5.xlarge', 'm5.2xlarge', 'm5.4xlarge',
    'm5a.large', 'm5a.xlarge', 'm5a.2xlarge', 'm5a.4xlarge',
    'm6a.large', 'm6a.xlarge', 'm6a.2xlarge', 'm6a.4xlarge',
    'm6i.large', 'm6i.xlarge', 'm6i.2xlarge', 'm6i.4xlarge',
    'r5.large', 'r5.xlarge', 'r5.2xlarge', 'r5.4xlarge',
    'r5a.large', 'r5a.xlarge', 'r5a.2xlarge', 'r5a.4xlarge',
    'r6i.large', 'r6i.xlarge', 'r6i.2xlarge', 'r6i.4xlarge',
    't3.large', 't3.xlarge', 't3.2xlarge'
]
instance_type_mapping = "instanceType"

[provider]
iam_instance_profile_id = "casmod-p2c1-h8gzk-worker-profile"
placement_zone = "us-east-2c"
placement_region = "us-east-2"
security_group_filter = "casmod-p2c1-h8gzk-worker-sg"
subnet_filter = "casmod-p2c1-h8gzk-private-us-east-2c"
owned_tag = "kubernetes.io/cluster/casmod-p2c1-h8gzk"
cluster_name_value = "casmod-p2c1"
