FROM quay.io/elmiko/kube-burner:latest AS builder

FROM registry.fedoraproject.org/fedora:latest

RUN dnf install -y python python3-pyyaml

COPY --from=builder /bin/kube-burner /bin/kube-burner

ADD --chmod=555 entrypoint.py /opt

ENTRYPOINT ["python", "/opt/entrypoint.py"]
